In [1]:
import numpy as np
a=np.array([1,4,5,8])
print(a)
type(a)

[1 4 5 8]


numpy.ndarray

In [2]:
import numpy as np
a=np.array([1,4,5,8])
a[3]

8

In [3]:
import numpy as np
a=np.array([1,4,5,8])
a[0]=5
print(a)

[5 4 5 8]


In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
a[0,0]

[[1 2 3]
 [4 5 6]]


1

In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a[0,1]

2

In [6]:
a=np.array([[1,2,3],[4,5,6]])
a[1:]

array([[4, 5, 6]])

In [7]:
a=np.array([[1,2,3],[4,5,6]])
a[:,2]


array([3, 6])

In [8]:
a[-1:,-2:]

array([[5, 6]])

In [9]:
a.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [11]:
a=np.array([[1,2,3],[4,5,6]])
len(a)

2

In [12]:
2 in a

True

In [13]:
0 in a

False

In [14]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a=a.reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
a.shape

(5, 2)

In [17]:
a=np.array([1,2,3])
b=a
c=a.copy()
a[0]=0
a

array([0, 2, 3])

In [18]:
b

array([0, 2, 3])

In [19]:
c

array([1, 2, 3])

In [20]:
a=np.array([1,2,3],float)
a.tolist()


[1.0, 2.0, 3.0]

In [21]:
list(a)

[1.0, 2.0, 3.0]

In [22]:
a=np.array([1,2,3])
s=a.tostring()
print(s)
np.fromstring(s)

C:\Users\MyLap\AppData\Local\Temp/ipykernel_9240/4008674564.py:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s=a.tostring()
C:\Users\MyLap\AppData\Local\Temp/ipykernel_9240/4008674564.py:4: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'


ValueError: string size must be a multiple of element size

In [ ]:
a=np.array([1,2,3])
print(a)

In [ ]:
a.fill(0)
a

In [ ]:
a=np.array(range(6)).reshape((2,3))
a

In [ ]:
a.transpose()

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a.flatten()

In [ ]:
a=np.array([1,2,3])
b=np.array([5,2,6])
a+b

In [ ]:
a-b

In [ ]:
a*b

In [ ]:
b/a

In [ ]:
a%b

In [ ]:
b**a

In [47]:
a=np.array([1,4,5],int)
for x in a:
    print(x)

1
4
5


In [55]:
import numpy as np
c=np.array([[1,2],[3,4],[5,6]])
for x in c:
    print(x)

[1 2]
[3 4]
[5 6]


In [56]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
for (x,y) in a:
    print(x*y)

2
12
30


In [28]:
a=np.array([2,4,3])
a.sum()

9

In [29]:
a.prod()

24

In [30]:
a=np.array([2,1,9])
a.mean()

4.0

In [31]:
a.var()

12.666666666666666

In [32]:
a.std()

3.559026084010437

In [33]:
a=np.array([2,1,9])
a.min()

1

In [34]:
a.max()

9

In [37]:
a=np.array([2,1,9])
a.argmin()

1

In [38]:
a.argmax()

2

In [39]:
a=np.array([[0,2],[3,-1],[3,5]])
a.mean(axis=0)

array([2., 2.])

In [40]:
a.mean(axis=1)

array([1., 1., 4.])

In [41]:
a.min(axis=1)

array([ 0, -1,  3])

In [42]:
a.max(axis=0)

array([3, 5])