In [1]:
import numpy as np
li=[1,3,5,7,9]
numpyArr = np.array(li)
print(numpyArr[0])
print(numpyArr[1])
print(numpyArr[2])
print(numpyArr[3])
print(numpyArr[4])

1
3
5
7
9


In [2]:
arr = [11, 22, 33, 44, 55]
print("Before reversal Array is :",arr) 
arr.reverse()
print("After reversing Array:",arr)

Before reversal Array is : [11, 22, 33, 44, 55]
After reversing Array: [55, 44, 33, 22, 11]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [4]:
import numpy as np
arr = np.array([10, 20, 40, 60, 80, 100])
avg = np.average(arr)
print('\nThe Average Of Array Elements = ', avg)


The Average Of Array Elements =  51.666666666666664


In [5]:
import numpy as np
secLarr = np.array([2,3,8,10])
print("Array Items = ", secLarr)
secLarr.sort()
print("The Second Largest Item in this Array = ", secLarr[len(secLarr) - 2])

Array Items =  [ 2  3  8 10]
The Second Largest Item in this Array =  8


In [6]:
import numpy as np
arr = np.array([10, 20, 40, 60, 80, 100])
print (min(arr))

10


In [7]:
import numpy as np
arr = np.array([10, 20, 40, 60, 80, 100])
print(max(arr))

100


In [8]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [9]:
import numpy as np
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21])
print(arr[0:len(arr):2])

[ 1  5  9 13 17 21]


In [10]:
import numpy as np
arr=np.array([2,4,6,8,10,12,14,16,18,20])
print(arr[0:len(arr):2])

[ 2  6 10 14 18]


In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [14]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = 3,4,5
a = np.delete(a, index)
print(a)

[ 10  20  30  70  80  90 100]


In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])               
my_list = my_array.tolist()
print(my_list)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(len(arr))

In [ ]:
import numpy
arr1_insert = numpy.array([1, 23, 33])  
arr2_insert = numpy.insert(arr1_insert, 1, 91)  
print(arr2_insert)